### ISSUE TITLE
Are you aware of JiraPS?

### ISSUE THREAD

**Issue by markwragg** [KevinMarquette/jira#3]
Are you aware of this module?:
https://github.com/AtlassianPS/JiraPS

It's pretty well maintained.

**Comment by KevinMarquette** [comment]
Absolutely, I use it all the time. I am trying to complement that module with bulk features that would be a challenge to add to that module (or atleast pilot it here and integrate it later). I go into it quite a bit more here: [powershellexplained.com: Jira module project](https://powershellexplained.com/2019-03-18-Powershell-jira-module/?utm_source=github&utm_medium=issue)

**Comment by markwragg** [comment]
Ah, awesome sounds great!
